

#siu by Sturm


#Этот говнокод не работает или работает неправильно? Напиши в дс Sturm#6360, разберёмся



#Предмет, который обозначает доступное улучшение в меню 
icon: 
  type: BLUE_STAINED_GLASS
  amount: 1
  name: "&aДоступное улучшение"


items:
    WOODEN_SWORD:
      default:
        #default используется при крафте предмета, но не работает при взятии предмета из креатива или при выдаче предмета через команду
        # 
        #ВАЖНО: 
        #1) Нельзя задать условия назначения предмету группы default. Вернее, задать можно, но они не будут работать.
        #2) reward отсюда выдаётся при крафте предмета. То есть по умолчанию при крафте деревянного меча
        #   игроку даётся железный слиток, а мечу назначаются модификаторы урон: +1 и скорость атаки: -3.5
        #3) Если из группы default не идут улучшения через open в блоке reward, то предмет не улучшается никак (логично)
        #4) lore в группе default не используется. Вы можете его прописать, но он не будет нигде показываться
        reward:
          #Устанавливает улучшаемому предмету атрибуты
          attributes: ["generic.attackdamage, 1", "generic.attackspeed, -3.5"]
          #ID открываемых улучшений
          #Эти улучшения взаимоисключаемые (потому что доступные улучшения берутся от последнего взятого улучшения)
          #Если вы хотите, чтобы доступны были оба, сделайте их последовательно (то есть оставьте одно из них (например, 22) тут, а второе вставьте
          #в блок open того, которое осталось тут
          #  default:
          #  ...
          #    open: 22
          #  22:
          #  ...
          #    open: 23
          #делает оба улучшения доступными
          open: ["22", "23"]
          #custom - ваша команда, выполняемая из консоли. Стандартно доступны заполнители %player%, %x%, %y%, %z% (угадайте, что за что отвечает)
          #Но вы можете использовать свои заполнители из PlaceholderAPI
          custom:
            - "give %player% iron_ingot"
      22: 
        #Здесь находится то, что необходимо собрать игроку для улучшения
        need:
          #Описание требований, которое показывается при введении игроком команды /upgrade
          lore:
            - ""
            - ""
          #Сколько денег требует улучшение. Не работает без Vault
          money: 100
          #Предметы, которые тратятся на улучшение
          items: ["STICK, 64", "DIAMOND_BLOCK, 1"]
          #Простые условия при помощи одного знака >, < или == с числами                         (%level% > 3, %exp_level% > 10).
          #Две функции - hasPermision(permission), equals(первоезначение, второезначение)        (hasPermision(siu.up22), equals(%vault_rank%, vip) ).
          #Я не знаю, как можно быстро перевести строку в логическое выражение, а писать это самостоятельно я не хочу
          #
          #Заполнители, доступные без PlaceholderAPI: %player%, %exp_level%, %world%, %x%, %y%, %z%
          custom:
            - "hasPermission(mycustompermission)"
            - "equals(%vault_rank%, vip)"
            #- "%level% > 2"
        reward:
          #Описание награды в меню
          lore:
            - "+1 $"
            - "+7 гнилой плоти"
            - "Установит урон меча: 2"  #1 по стандарту, +1 атрибут
            - "Установит скорость атаки меча: 0.5"  #4 по стандарту, -3.5 атрибут
            - "Выдаст вам яблоко"
            - "Установит в вашей локации блок камня"
          #Сколько игроку даётся за улучшение 
          #  (не пишите никуда null, если вам не нужна строчка, просто удалите её или оставьте пустой (для money можно поставить 0))
          money: 1
          #Предметы, которые выдаются при улучшении
          items: ["ROTTEN_FLESH, 7"]
          #Атрибуты, которые ставятся на предмет (может работать криво)
          attributes: ["generic.attackdamage, 1", "generic.attackspeed, -3.5"]
          #Зачарования, которые получает предмет
          enchantments: ["unbreaking, 4"]
          #Улучшения, которые становятся доступны
          open: ["24"]     
          #Ваша команда, исполняемая из консоли. По умолчанию доступны заполнители %player%, %x%, %y%, %z%. Можно использовать PlaceholderAPI.
          custom: 
            - "setblock %x% %y% %z% stone"
            - "give %player% apple 4"
      23: 
        need:
          lore: 
            - "100 монет"
            - "Стак палок"
            - "Один алмазный блок"
          money: 100
          items: ["STICK, 64", "DIAMOND_BLOCK, 1"]
          custom:
            - ""
        reward:
          lore:
            - "1 монетка"
            - "7 шт гнилой плоти"
            - "Урон: 5"
            - "Скорость атаки: 2"
          money: 1
          items: ["ROTTEN_FLESH, 7"]
          attributes: ["generic.attackdamage, 4", "generic.attackspeed, -2"]
      24: 
        need:
          lore: 
            - "Ничего"
        reward:
          lore:
            - "123$"
            - "Удар по голове молнией из essentials"
          money: 123
          #Команды из плагинов работают только при наличии плагинов (что весьма логично)
          custom: "essentials:thor %player%"
      
                